[workspace]
resolver = "3"
members = [ "crates/board", "crates/engine", "crates/evaluation", "crates/nnueffi", "crates/raw", "crates/tpt", "crates/types", "crates/uci", "crates/utilities", "crates/zobrist"]

[profile.release]
opt-level = 3        # max LLVM optimizations
lto = "fat"          # full link-time optimization
codegen-units = 1    # single-threaded codegen, better optimization at the cost of compile time
panic = "abort"      # smaller, faster, no unwinding machinery
incremental = false  # disable incremental compilation (cleaner codegen)
strip = "symbols"    # strip debug symbols for smaller binary
